/*
 * SPDX-FileCopyrightText: 2022-2024 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_AUDIO_FILES           3
#define MMAP_AUDIO_CHECKSUM        0x50D5

enum MMAP_AUDIO_LISTS {
    MMAP_AUDIO_ECHO_WAV = 0,        /*!< echo.wav */
    MMAP_AUDIO_ERROR_WAV = 1,        /*!< error.wav */
    MMAP_AUDIO_SUCCESS_WAV = 2,        /*!< success.wav */
};
