// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_muyuplay_screen_init(void)
{
    ui_muyuplay = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_muyuplay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_muyuplay);
    lv_obj_set_width(ui_Panel3, 240);
    lv_obj_set_height(ui_Panel3, 240);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_muyu = lv_img_create(ui_Panel3);
    lv_img_set_src(ui_muyu, &ui_img_muyu_png);
    lv_obj_set_width(ui_muyu, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_muyu, LV_SIZE_CONTENT);    /// 256
    lv_obj_align(ui_muyu, LV_ALIGN_CENTER, 0, 20);
    lv_obj_add_flag(ui_muyu, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_muyu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_muyu, 200);

    ui_gongdetxt = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_gongdetxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gongdetxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gongdetxt, -54);
    lv_obj_set_y(ui_gongdetxt, -50);
    lv_obj_set_align(ui_gongdetxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gongdetxt, "功德+1");
    lv_obj_set_style_text_color(ui_gongdetxt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gongdetxt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gongdetxt, &ui_font_OPPOSansH25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_gongdetxt, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_muyuplay, ui_event_muyuplay, LV_EVENT_ALL, NULL);

    ui_gongde_sum = lv_label_create(ui_Panel3);
    lv_label_set_recolor(ui_gongde_sum, true); 
    
    lv_label_set_text_fmt(ui_gongde_sum, "#f1c40f 今日功德: %d#", gongde_sum);
    lv_obj_set_style_text_font(ui_gongde_sum, &ui_font_OPPOSansH18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_align_to(ui_gongde_sum, ui_muyu, LV_ALIGN_TOP_RIGHT, -30, 25);

}
