// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

#include "esp_err.h"
#include "esp_check.h"
#include "ui.h"
#include "ui_helpers.h"
#include "bsp/esp-bsp.h"
#include "lv_lottie.h"
#include "esp_camera.h"
#include "thorvg_capi.h"

#include "mmap_generate_lottie_assets.h"

#define TAG "ui"

#define LOTTIE_SIZE_HOR         (180)
#define LOTTIE_SIZE_VER         (180)

extern mmap_assets_handle_t asset_lottie;
///////////////////// VARIABLES ////////////////////

// SCREEN: ui_home
void ui_home_screen_init(void);
void ui_event_home(lv_event_t *e);
lv_obj_t *ui_home;

ui_page_name_t ui_pages[2];

// SCREEN:ui_face
void ui_face_screen_init(void);
lv_obj_t *ui_face;
lv_obj_t *ui_Panel_face;
lv_obj_t *ui_face_canvas;
void ui_event_face(lv_event_t *e);
lv_obj_t *ui_img_face;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
#error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_home(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_SCREEN_LOAD_START) {

    }
    if (event_code == LV_EVENT_SCREEN_FACE) {
        _ui_screen_change(&ui_face, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_face_screen_init);
    }
}

void ui_event_face(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);

    if (event_code == LV_EVENT_SCREEN_LOAD_START) {

        void *data = mmap_assets_get_mem(asset_lottie, MMAP_LOTTIE_ASSETS_LOOK_JSON);
        size_t size = mmap_assets_get_size(asset_lottie, MMAP_LOTTIE_ASSETS_LOOK_JSON);
        lv_lottie_set_src_data(ui_face_canvas, data, size);
    }

    if (event_code == LV_EVENT_FACE_LOOK) {
        void *data = mmap_assets_get_mem(asset_lottie, MMAP_LOTTIE_ASSETS_LOOK_JSON);
        size_t size = mmap_assets_get_size(asset_lottie, MMAP_LOTTIE_ASSETS_LOOK_JSON);
        lv_lottie_set_src_data(ui_face_canvas, data, size);
    }

    if (event_code == LV_EVENT_FACE_ASK) {
        void *data = mmap_assets_get_mem(asset_lottie, MMAP_LOTTIE_ASSETS_ASK_JSON);
        size_t size = mmap_assets_get_size(asset_lottie, MMAP_LOTTIE_ASSETS_ASK_JSON);
        lv_lottie_set_src_data(ui_face_canvas, data, size);
    }

    if (event_code == LV_EVENT_FACE_THINK) {
        void *data = mmap_assets_get_mem(asset_lottie, MMAP_LOTTIE_ASSETS_THINK_JSON);
        size_t size = mmap_assets_get_size(asset_lottie, MMAP_LOTTIE_ASSETS_THINK_JSON);
        lv_lottie_set_src_data(ui_face_canvas, data, size);
    }

    if (event_code == LV_EVENT_FACE_RUNNING) {
        void *data = mmap_assets_get_mem(asset_lottie, MMAP_LOTTIE_ASSETS_RUNNING_JSON);
        size_t size = mmap_assets_get_size(asset_lottie, MMAP_LOTTIE_ASSETS_RUNNING_JSON);
        lv_lottie_set_src_data(ui_face_canvas, data, size);
        lv_lottie_set_segment(ui_face_canvas, 18, 37, false);
    }
}

///////////////////// SCREENS ////////////////////

typedef struct {
    lv_obj_t *obj;
    lv_event_code_t event_code;
    void *user_data;
    void *param;
} lv_sys_event_t;

static QueueHandle_t ui_sys_event = NULL;

void ui_system_update(lv_timer_t *timer)
{
    lv_sys_event_t event;
    if (pdPASS == xQueueReceive(ui_sys_event, &event, 0)) {
        lv_event_send(event.obj, event.event_code, event.user_data);
    }
}

void ui_send_sys_event(lv_obj_t *obj, lv_event_code_t event_code, void *user_data)
{
    lv_sys_event_t eventOut;

    eventOut.obj = obj;
    eventOut.event_code = event_code;
    eventOut.user_data = user_data;

    xQueueSend(ui_sys_event, &eventOut, 0);

    return;
}

void ui_init(void)
{

    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                              false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_home_screen_init();

    ui_face_screen_init();

    ui_pages[0].page = ui_home;
    ui_pages[0].name = "home";
    ui_pages[1].page = ui_face;
    ui_pages[1].name = "face";

    lv_disp_load_scr(ui_home);

    ui_sys_event = xQueueCreate(4, sizeof(lv_sys_event_t));
    ESP_ERROR_CHECK_WITHOUT_ABORT((ui_sys_event) ? ESP_OK : ESP_FAIL);

    lv_timer_create(ui_system_update, 10,  NULL);
    ui_send_sys_event(ui_home, LV_EVENT_SCREEN_FACE, NULL);
}
