// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "esp_log.h"

#include "ui_helpers.h"
#include "ui_events.h"

#define LV_EVENT_RENEW                  (_LV_EVENT_LAST + 1)
#define LV_EVENT_SCREEN_NEXT            (_LV_EVENT_LAST + 2)
#define LV_EVENT_SCREEN_PRIVIOUS        (_LV_EVENT_LAST + 3)
#define LV_EVENT_SET_FRAME              (_LV_EVENT_LAST + 4)
#define LV_EVENT_SCREEN_FACE            (_LV_EVENT_LAST + 5)

#define LV_EVENT_FACE_LOOK              (_LV_EVENT_LAST + 6)
#define LV_EVENT_FACE_ASK               (_LV_EVENT_LAST + 7)
#define LV_EVENT_FACE_THINK             (_LV_EVENT_LAST + 8)
#define LV_EVENT_FACE_RUNNING           (_LV_EVENT_LAST + 9)

#define LOTTIE_SIZE_HOR_MIN             (90)
#define LOTTIE_SIZE_VER_MIN             (90)

// SCREEN: ui_home
void ui_home_screen_init(void);
void ui_event_home(lv_event_t *e);
extern lv_obj_t *ui_home;

// SCREEN: ui_face
void ui_face_screen_init(void);
extern lv_obj_t *ui_face;
extern lv_obj_t *ui_Panel_face;
extern lv_obj_t *ui_face_canvas;
void ui_event_face(lv_event_t *e);
void ui_send_sys_event(lv_obj_t *obj, lv_event_code_t event_code, void *user_data);

LV_FONT_DECLARE(ui_font_ComfortaaBold75);
LV_FONT_DECLARE(ui_font_ComfortaaLight70);
LV_FONT_DECLARE(ui_font_OPPOSansH18);
LV_FONT_DECLARE(ui_font_OPPOSansH25);
LV_FONT_DECLARE(ui_font_OPPOSansL70);

typedef struct {
    lv_obj_t *page;
    char *name;
} ui_page_name_t;

extern ui_page_name_t ui_pages[2];

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
