// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void flow1_Animation(lv_obj_t * TargetObject, int delay);
void flow2_Animation(lv_obj_t * TargetObject, int delay);
void flow3_Animation(lv_obj_t * TargetObject, int delay);
void flow4_Animation(lv_obj_t * TargetObject, int delay);
void flow5_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_LabelUserName;
extern lv_obj_t * ui_LabelFansCount;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bilibili_png);    // assets/bilibili.png
LV_IMG_DECLARE(ui_img_bilibiliname_png);    // assets/bilibiliName.png
LV_IMG_DECLARE(ui_img_bilibili_name_2_png);    // assets/bilibili_name_2.png

// FONTS
LV_FONT_DECLARE(ui_font_PHFont10);
LV_FONT_DECLARE(ui_font_PHFont14);
LV_FONT_DECLARE(ui_font_PHFont16);
LV_FONT_DECLARE(ui_font_PHFont28);
LV_FONT_DECLARE(ui_font_PHFont17);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
