/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_LOTTIE_ASSETS_FILES           11
#define MMAP_LOTTIE_ASSETS_CHECKSUM        0xACF4

enum MMAP_LOTTIE_ASSETS_LISTS {
    MMAP_LOTTIE_ASSETS_DICE1_BMP = 0,        /*!< dice1.bmp */
    MMAP_LOTTIE_ASSETS_DICE2_BMP = 1,        /*!< dice2.bmp */
    MMAP_LOTTIE_ASSETS_DICE3_BMP = 2,        /*!< dice3.bmp */
    MMAP_LOTTIE_ASSETS_DICE4_BMP = 3,        /*!< dice4.bmp */
    MMAP_LOTTIE_ASSETS_DICE5_BMP = 4,        /*!< dice5.bmp */
    MMAP_LOTTIE_ASSETS_DICE6_BMP = 5,        /*!< dice6.bmp */
    MMAP_LOTTIE_ASSETS_ASK_JSON = 6,        /*!< ask.json */
    MMAP_LOTTIE_ASSETS_FISH_JSON = 7,        /*!< fish.json */
    MMAP_LOTTIE_ASSETS_LOOK_JSON = 8,        /*!< look.json */
    MMAP_LOTTIE_ASSETS_SPEAK_JSON = 9,        /*!< speak.json */
    MMAP_LOTTIE_ASSETS_THINK_JSON = 10,        /*!< think.json */
};
