/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_WEATHER_FILES           61
#define MMAP_WEATHER_CHECKSUM        0x42AB

enum MMAP_WEATHER_LISTS {
    MMAP_WEATHER_100_QOI = 0,        /*!< 100.qoi */
    MMAP_WEATHER_101_QOI = 1,        /*!< 101.qoi */
    MMAP_WEATHER_102_QOI = 2,        /*!< 102.qoi */
    MMAP_WEATHER_103_QOI = 3,        /*!< 103.qoi */
    MMAP_WEATHER_104_QOI = 4,        /*!< 104.qoi */
    MMAP_WEATHER_150_QOI = 5,        /*!< 150.qoi */
    MMAP_WEATHER_151_QOI = 6,        /*!< 151.qoi */
    MMAP_WEATHER_154_QOI = 7,        /*!< 154.qoi */
    MMAP_WEATHER_300_QOI = 8,        /*!< 300.qoi */
    MMAP_WEATHER_301_QOI = 9,        /*!< 301.qoi */
    MMAP_WEATHER_302_QOI = 10,        /*!< 302.qoi */
    MMAP_WEATHER_303_QOI = 11,        /*!< 303.qoi */
    MMAP_WEATHER_304_QOI = 12,        /*!< 304.qoi */
    MMAP_WEATHER_305_QOI = 13,        /*!< 305.qoi */
    MMAP_WEATHER_306_QOI = 14,        /*!< 306.qoi */
    MMAP_WEATHER_307_QOI = 15,        /*!< 307.qoi */
    MMAP_WEATHER_308_QOI = 16,        /*!< 308.qoi */
    MMAP_WEATHER_309_QOI = 17,        /*!< 309.qoi */
    MMAP_WEATHER_310_QOI = 18,        /*!< 310.qoi */
    MMAP_WEATHER_311_QOI = 19,        /*!< 311.qoi */
    MMAP_WEATHER_312_QOI = 20,        /*!< 312.qoi */
    MMAP_WEATHER_313_QOI = 21,        /*!< 313.qoi */
    MMAP_WEATHER_314_QOI = 22,        /*!< 314.qoi */
    MMAP_WEATHER_315_QOI = 23,        /*!< 315.qoi */
    MMAP_WEATHER_316_QOI = 24,        /*!< 316.qoi */
    MMAP_WEATHER_317_QOI = 25,        /*!< 317.qoi */
    MMAP_WEATHER_318_QOI = 26,        /*!< 318.qoi */
    MMAP_WEATHER_350_QOI = 27,        /*!< 350.qoi */
    MMAP_WEATHER_351_QOI = 28,        /*!< 351.qoi */
    MMAP_WEATHER_399_QOI = 29,        /*!< 399.qoi */
    MMAP_WEATHER_400_QOI = 30,        /*!< 400.qoi */
    MMAP_WEATHER_401_QOI = 31,        /*!< 401.qoi */
    MMAP_WEATHER_402_QOI = 32,        /*!< 402.qoi */
    MMAP_WEATHER_403_QOI = 33,        /*!< 403.qoi */
    MMAP_WEATHER_404_QOI = 34,        /*!< 404.qoi */
    MMAP_WEATHER_405_QOI = 35,        /*!< 405.qoi */
    MMAP_WEATHER_406_QOI = 36,        /*!< 406.qoi */
    MMAP_WEATHER_407_QOI = 37,        /*!< 407.qoi */
    MMAP_WEATHER_408_QOI = 38,        /*!< 408.qoi */
    MMAP_WEATHER_409_QOI = 39,        /*!< 409.qoi */
    MMAP_WEATHER_410_QOI = 40,        /*!< 410.qoi */
    MMAP_WEATHER_456_QOI = 41,        /*!< 456.qoi */
    MMAP_WEATHER_457_QOI = 42,        /*!< 457.qoi */
    MMAP_WEATHER_499_QOI = 43,        /*!< 499.qoi */
    MMAP_WEATHER_500_QOI = 44,        /*!< 500.qoi */
    MMAP_WEATHER_501_QOI = 45,        /*!< 501.qoi */
    MMAP_WEATHER_502_QOI = 46,        /*!< 502.qoi */
    MMAP_WEATHER_503_QOI = 47,        /*!< 503.qoi */
    MMAP_WEATHER_504_QOI = 48,        /*!< 504.qoi */
    MMAP_WEATHER_507_QOI = 49,        /*!< 507.qoi */
    MMAP_WEATHER_508_QOI = 50,        /*!< 508.qoi */
    MMAP_WEATHER_509_QOI = 51,        /*!< 509.qoi */
    MMAP_WEATHER_510_QOI = 52,        /*!< 510.qoi */
    MMAP_WEATHER_511_QOI = 53,        /*!< 511.qoi */
    MMAP_WEATHER_512_QOI = 54,        /*!< 512.qoi */
    MMAP_WEATHER_513_QOI = 55,        /*!< 513.qoi */
    MMAP_WEATHER_514_QOI = 56,        /*!< 514.qoi */
    MMAP_WEATHER_515_QOI = 57,        /*!< 515.qoi */
    MMAP_WEATHER_900_QOI = 58,        /*!< 900.qoi */
    MMAP_WEATHER_901_QOI = 59,        /*!< 901.qoi */
    MMAP_WEATHER_999_QOI = 60,        /*!< 999.qoi */
};
